document.write("<div class='frame'>")
document.write("<p class='frame-title'></p>")
document.write("<table style='width: 100%'>")
document.write("<tr>")
document.write("<td valign='top' align='center'><img src='images/profile.png'></td>")
document.write("<td style='vertical-align:middle'>")
document.write("<div valign='top' class='texte-avec-ligne-verticale'")
document.write("style='margin-left: 20px; margin-top: -10px; margin-bottom:20px; vertical-align: text-bottom ;'>")
document.write("<p valign='top'>")
document.write("Intéressé par mon profil ?")
document.write("<br><br>")
document.write("<a href='mailto:jonathan.graff@hotmail.fr?subject=Contact'>Contactez-moi par email</a> ou directement")
document.write(" par téléphone au <a href='tel:+33766474681'>07 66 47 46 81</a>")
document.write("</p></div></td></tr></table></div>")